### ISSUE TITLE
Bridge does not initialize after multipage navigation

### ISSUE THREAD

**Issue by b1ackout** [binh-vu/streamlit-bridge#6]
I tried to use a bridge on a multipage application with the buttons example. 

When the page loads the Home page, everything works as expected.

![image](https://user-images.githubusercontent.com/8949953/212717875-782740f2-0eb0-4a5f-8245-4cd8a35cc1b1.png)

But when I navigate to "Page 1" and back to Home and press a button the bridge does not update and the error `Uncaught TypeError: Cannot read properties of null (reading 'postMessage')` pops up.

![image](https://user-images.githubusercontent.com/8949953/212718290-8b5187ae-d372-4f00-a2e2-a2bf17ab748b.png)

It's like stBridges fails to initialize the second time.

**Comment by binh-vu** [comment]
Thanks for reporting it! It looks like that you already have the code to produce the error. Can you please share with me so I can quickly reproduce and fix it on my side? Thanks!

**Comment by b1ackout** [comment]
[test.zip](https://github.com/binh-vu/streamlit-bridge/files/10429545/test.zip)

Sure, here you go.

**Comment by binh-vu** [comment]
Hey @b1ackout, thank you a lots for providing the example. This is a simple issue but I haven't been able to touch my laptop for a couple of days. Sorry for the delay! It has been fixed in the version 1.1.3! Thanks again for reporting the issue.
